names=["Ali","Yağmur","Hakan","Deniz"]
years=[1998,2000,1998,1987]
names.append("Cenk")
names.insert(0,"Sena")
print(names)
#names.pop(4)
print(names)
print(names.index("Deniz"))
print("Ali" in names)
names.reverse()
print(names)
names.sort()
print(names)
years.sort()
print(years)
str="Chevrolet,Dacia"
list=str.split(",")
print(list)
print("Lowest",years[0])
print("Highest",years[-1])
print(years.count(1998))
years.clear()
print(years)
a=input("Companys: ")
b=input("Companys: ")
c=input("Companys: ")
d=a+","+b+","+c
e=d.split(",")
print(e)